apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-layer
  namespace: data-layer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-layer
  template:
    metadata:
      labels:
        app: data-layer
    spec:
      serviceAccountName: data-layer
      containers:
      - name: data-layer
        image: 715841361707.dkr.ecr.eu-north-1.amazonaws.com/data-layer:latest
        ports:
        - containerPort: 80
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: AWS_REGION
          value: "eu-north-1"
        - name: S3_BUCKET
          value: "fortifai-data"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: aws-credentials
        secret:
          secretName: aws-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: data-layer
  namespace: data-layer
spec:
  selector:
    app: data-layer
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP 