apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ai-detector-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-detector-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: ai-detector-sa
  namespace: microservices
roleRef:
  kind: ClusterRole
  name: ai-detector-cluster-role
  apiGroup: rbac.authorization.k8s.io 